---
- name: "prometheus | Deploy Alertmanager templates"
  ansible.builtin.copy:
    content: "{{ vars['alertmanager_instance_templates'] }}"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] + '/' +
      'alertmanager.tmpl' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "vars['alertmanager_instance_templates'] is defined"
    - "vars['alertmanager_instance_templates'] != []"
    - "vars['alertmanager_instance_templates'] != ''"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager Gossip TLS settings"
  ansible.builtin.template:
    src: "gossip.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] + '/' +
      'gossip.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "vars['alertmanager_instance_gossip'] is defined"
    - "vars['alertmanager_instance_gossip'] != []"
    - "vars['alertmanager_instance_gossip'] != ''"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager YAML configuration"
  ansible.builtin.template:
    src: "alertmanager.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] + '/' +
      'alertmanager.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "amtool check-config %s"
  when:
    - "vars['alertmanager_instance_settings'] is defined"
    - "vars['alertmanager_instance_settings'] != []"
    - "vars['alertmanager_instance_settings'] != ''"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager service configuration"
  ansible.builtin.template:
    src: "alertmanager_options.j2"
    dest: "{{ hostvars[inventory_hostname]['prometheus_options_dest'] + '/' +
      hostvars[inventory_hostname]['alertmanager_service'] }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Restart Alertmanager"
- name: "prometheus | Ensure Alertmanager service is started"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['alertmanager_service'] }}"
    state: "started"
  when:
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['alertmanager_started']) is defined"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['alertmanager_started']) == 'true'"
  vars:
    alertmanager_started: "[].started[] |
      map(&alertmanager || 'false', @) | [0]"
- name: "prometheus | Enable Alertmanager service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['alertmanager_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['alertmanager_enable']) is defined"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['alertmanager_enable']) == 'true'"
  vars:
    alertmanager_enable: "[].enable[] | map(&alertmanager || 'false', @) | [0]"
