---
- name: "prometheus | Deploy Prometheus rules configuration"
  ansible.builtin.template:
    src: "prometheus_groups.j2"
    dest: "{{ hostvars[inventory_hostname]['prometheus_conf_dest'] + '/' +
      'prometheus_rules.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "{{ 'promtool check rules' }}
      {%- if vars['prometheus_lint'] is defined and vars['prometheus_lint']
      in ['all', 'duplicate-rules', 'none'] -%}
      {{ ' --lint=' + vars['prometheus_lint'] }}{%- endif -%} {{ ' %s' }}"
  when:
    - "vars['prometheus_rules_settings'] is defined"
    - "vars['prometheus_rules_settings'] != ''"
  notify:
    - "Reload Prometheus"
- name: "prometheus | Deploy Prometheus configuration"
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['prometheus_conf_dest'] + '/' +
      'prometheus.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "{{ 'promtool check config' }}
      {%- if vars['prometheus_lint'] is defined and vars['prometheus_lint']
      in ['all', 'duplicate-rules', 'none'] -%}
      {{ ' --lint=' + vars['prometheus_lint'] }}{%- endif -%} {{ ' %s' }}"
  when:
    - "vars['prometheus_instance_settings'] is defined"
    - "vars['prometheus_instance_settings'] != ''"
  notify:
    - "Reload Prometheus"
- name: "prometheus | Deploy Prometheus service configuration"
  ansible.builtin.template:
    src: "prometheus.service.j2"
    dest: "{{ vars['prometheus_systemd_dir'] + '/' +
      hostvars[inventory_hostname]['prometheus_service'] + '.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "vars['prometheus_service_settings'] is defined"
    - "vars['prometheus_service_settings'] != []"
  notify:
    - "Restart Prometheus"
- name: "prometheus | Ensure Prometheus service is started"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['prometheus_service'] }}"
    state: "started"
  when:
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['prometheus_started']) is defined"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['prometheus_started']) == 'true'"
  vars:
    prometheus_started: "[].started[] | map(&prometheus || 'false', @) | [0]"
- name: "prometheus | Enable Prometheus service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['prometheus_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['prometheus_enable']) is defined"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(vars['prometheus_enable']) == 'true'"
  vars:
    prometheus_enable: "[].enable[] | map(&prometheus || 'false', @) | [0]"
