---
- include_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['prometheus_install_package'] is defined"
  - "hostvars[inventory_hostname]['prometheus_install_package'] == 'true'"
- include_tasks: deploy_prometheus.yml
  when:
  - "hostvars[inventory_hostname]['prometheus'] is defined"
  - "hostvars[inventory_hostname]['prometheus'] != ''"
