---
- name: "prometheus | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "prometheus | Install Prometheus package"
  block:
    - name: "prometheus | Set fact for packages task [Prometheus package]"
      ansible.builtin.set_fact:
        prometheus_package_name:
          "{{ hostvars[inventory_hostname]['prometheus_package'] }}"
    - name: "prometheus | Include packages tasks [Prometheus package]"
      ansible.builtin.include_tasks:
        file: "packages.yml"
      when:
        - "hostvars[inventory_hostname]['prometheus'] is defined"
        - "hostvars[inventory_hostname]['prometheus'] != ''"
        - "hostvars[inventory_hostname]['prometheus'] |
           community.general.json_query(vars['prometheus_install_package'])
           is defined"
        - "hostvars[inventory_hostname]['prometheus'] |
           community.general.json_query(vars['prometheus_install_package']) ==
           'true'"
      vars:
        prometheus_install_package:
          "[].install_package[] | map(&prometheus || 'false', @) | [0]"
- name: "prometheus | Install Alertmanager package"
  block:
    - name: "prometheus | Set fact for packages task [Alertmanager package]"
      ansible.builtin.set_fact:
        prometheus_package_name:
          "{{ hostvars[inventory_hostname]['alertmanager_package'] }}"
    - name: "prometheus | Include packages tasks [Alertmanager package]"
      ansible.builtin.include_tasks:
        file: "packages.yml"
      when:
        - "hostvars[inventory_hostname]['prometheus'] is defined"
        - "hostvars[inventory_hostname]['prometheus'] != ''"
        - "hostvars[inventory_hostname]['prometheus'] |
           community.general.json_query(vars['alertmanager_install_package']) is
           defined"
        - "hostvars[inventory_hostname]['prometheus'] |
           community.general.json_query(vars['alertmanager_install_package']) ==
           'true'"
      vars:
        alertmanager_install_package:
          "[].install_package[] | map(&alertmanager || 'false', @) | [0]"
- name: "prometheus | Include Prometheus deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy_prometheus.yml"
- name: "systemd_helper | Flush handlers"
  ansible.builtin.meta: "flush_handlers"
- name: "prometheus | Include Alertmanager deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy_alertmanager.yml"
